export enum MotorRiskType {
  X1_PRIVATE = 'X1_PRIVATE',

  X4_PRIVATE_CORPORATE = 'X4_PRIVATE_CORPORATE',

  TAXI = 'TAXI',

  HIRING_CARS = 'HIRING_CARS',

  BUS = 'BUS',

  MOTOR_CYCLE = 'MOTOR_CYCLE',

  AMBULANCE = 'AMBULANCE',

  OWN_GOODS_SMALL = 'OWN_GOODS_SMALL',

  OWN_GOODS_BIG = 'OWN_GOODS_BIG',

  ARTICULATOR = 'ARTICULATOR',

  TANKER = 'TANKER',

  GEN_CARTAGE_SMALL = 'GEN_CARTAGE_SMALL',

  GEN_CARTAGE_BIG = 'GEN_CARTAGE_BIG',

  Z_802_ON_SITE = 'Z_802_ON_SITE',

  Z_802_ON_ROAD = 'Z_802_ON_ROAD',

  GW1_CLASS_ONE = 'GW1_CLASS_ONE',

  GW1_CLASS_TWO = 'GW1_CLASS_TWO',

  GW1_CLASS_THREE = 'GW1_CLASS_THREE',
}
