export enum ETariffType {
  COMPREHENSIVE = 'COMPREHENSIVE',

  THIRD_PARTY = 'THIRD_PARTY',

  FIRE_AND_THEFT = 'FIRE_AND_THEFT',

  EXCLUSIVE_SPECIAL = 'EXCLUSIVE_SPECIAL',
}

export enum ERiskType {
  X1_PRIVATE = 'X1_PRIVATE',

  X4_PRIVATE_CORPORATE = 'X4_PRIVATE_CORPORATE',

  TAXI = 'TAXI',

  HIRING_CARS = 'HIRING_CARS',

  BUS = 'BUS',
}

export enum EPolicyPeriod {
  YEAR_1 = '1 YEAR',

  MONTHS_6 = '6 MONTHS',

  MONTHS_3 = '3 MONTHS',
}
