export enum TariffType {
  COMPREHENSIVE = 'COMPREHENSIVE',

  THIRD_PARTY = 'THIRD_PARTY',

  THIRD_PARTY_FIRE_AND_THEFT = 'THIRD_PARTY_FIRE_AND_THEFT',

  EXCLUSIVE_SPECIAL = 'EXCLUSIVE_SPECIAL',
}
